[package]
name = "ad-assistant"
version = "1.0.0"
description = "AD 域控助手"
authors = []
edition = "2021"

[lib]
name = "ad_assistant_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ldap3 = "0.11"
tokio = { version = "1", features = ["full"] }
csv = "1"
calamine = "0.26"
native-tls = "0.2"
dirs = "5"
chrono = "0.4"
